spring:
  resources:
    static-locations: classpath:/templates/
  thymeleaf:
    suffix: .html
    encoding: UTF-8
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bookuu?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器地址
    host: 127.0.0.1
    ## 连接超时时间（毫秒）
    timeout: 1200
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 8
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.bookuu.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countsql
  page-size-zero: true